server:
  port: 8080

spring:

  application:
    name: fks-kanban-server

  profiles:
    active: dev

  data:
    rest:
      defaultMediaType: application/json
    web:
      pageable:
        default-page-size: 25

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
