spring:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false

  datasources:
    - tenantId: nitroyard
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
      username: sa
      password: sa
      driverClassName: org.h2.Driver
      tomcat:
        connection-properties: useUnicode=true;characterEncoding=utf-8;

  cache:
    type: simple
