class Usuario{
    String username
    String password
    Usuario(String username, String password) 
}

class Quadro{
    String titulo
    String descricao
    Usuario dono
    LocalDateTime dataDeCriacao
    Set<Usuario> membros
    Boolean aberto
    Quadro(String titutlo, String descricao, Usuario dono)
    adicionarMembro(Usuario membro)
    removerMembro(Usuario membro)
    transferirTitularidade(Usuario membro)
    arquivar()
    reabrir()
}

class Coluna{
    String titulo
    Quadro quadro 
    Coluna(String titulo, Quadro quadro)

}

class Cartao{
    String titulo
    String descricao
    Coluna coluna 
    List<Comentario> comentarios
    Cartao(String titulo, String descricao, Coluna coluna)
    editar(String titulo, String descricao)
    mover(Coluna coluna)
    comentar(Comentario comentario)
    excluirComentario(Comentario comentario)
    substituirComentario(Comentario comentario)
}

class Comentario{
    String descricao
    LocalDateTime dataDeCriacao 
    Usuario criador
    Comentario(String descricao, Usuario criador)
    editar(String descricao)
}

Usuario "1" --* "N" Quadro
Quadro "1" --* "N" Usuario
Coluna "N" *-- "1" Quadro
Cartao "N" *-- "1" Coluna
Comentario "N" *-- "1" Usuario
Cartao "1" --* "N" Comentario
